<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File Uploader_file</name>
   <tag></tag>
   <elementGuidId>3718843a-fb82-4045-9493-dc55860bc1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file-upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file-upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6382c67c-6a5e-456f-9ad6-36914bf5fe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file-upload</value>
      <webElementGuid>5cba4b56-58bb-42a0-8374-147341241c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e6cb65a9-acbc-4441-a20c-524e542c8685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>657d6eaf-78a8-4961-a072-ad78e0105639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file-upload&quot;)</value>
      <webElementGuid>6de86728-1064-4dd4-9124-6651245fbad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file-upload']</value>
      <webElementGuid>fc64b9a3-fc04-474c-b0e5-5a42adaf5047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/form/input</value>
      <webElementGuid>1dc2a9a8-d7df-4e50-a923-24ca113947e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9fd55528-879a-4589-9da8-1c5644409036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'file-upload' and @type = 'file' and @name = 'file']</value>
      <webElementGuid>e34c4ae5-ecd7-4d00-bf7e-db5335ad389e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
