<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_luminoslogo.png</name>
   <tag></tag>
   <elementGuidId>c5b44f53-00c1-437f-a904-dd2fc76abed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a48e403e-d0be-45dd-a7c5-d722db7c63b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/luminoslogo.png</value>
      <webElementGuid>7bb1f714-9454-48e0-88ba-68a5386a7919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>luminoslogo.png</value>
      <webElementGuid>078c0ab8-18d7-42e1-b82e-e97974155c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/a[7]</value>
      <webElementGuid>a97cf832-a137-459b-8f53-1ea7ae70961a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/a[7]</value>
      <webElementGuid>9f397cfc-d4d6-4c6f-8ec8-26866fa4d78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'luminoslogo.png')]</value>
      <webElementGuid>7ea06168-ac96-40d9-90bb-e9e668a85760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lorem.docx'])[1]/following::a[1]</value>
      <webElementGuid>e1145c91-1054-4c28-b286-7e113f85a626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Screenshot 2022-04-16 151614.png'])[1]/following::a[2]</value>
      <webElementGuid>1741ec72-5ba5-4ab4-993a-c25e17f7a342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdf.png'])[1]/preceding::a[1]</value>
      <webElementGuid>03bc036b-dc20-44b0-86b8-6f766b673eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cowo-cewe.png'])[1]/preceding::a[2]</value>
      <webElementGuid>529c6a5a-e552-4c9a-b6d4-364d3be62493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='luminoslogo.png']/parent::*</value>
      <webElementGuid>c004cffa-27f7-4fbe-995a-e5c0ecd1b554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/luminoslogo.png')]</value>
      <webElementGuid>53b63c1b-7ba8-48c0-b1dc-a6f1987e4769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>acf367c2-aa51-4f63-873a-708e5ff776e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/luminoslogo.png' and (text() = 'luminoslogo.png' or . = 'luminoslogo.png')]</value>
      <webElementGuid>a28cc2d7-b3c8-4583-9d59-c5729f1188b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
