<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Screenshot_20221128_105312.png</name>
   <tag></tag>
   <elementGuidId>c6596832-b2a5-4442-b9a5-e968bc4774e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/a[31]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>103c7734-0160-4db1-a182-6c978a959a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/Screenshot_20221128_105312.png</value>
      <webElementGuid>3c1e1017-2dd3-4c69-b46c-9e57e4cca16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Screenshot_20221128_105312.png</value>
      <webElementGuid>da890b81-333a-4194-8bed-e77ed3e89674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/a[31]</value>
      <webElementGuid>ca5c6fef-8eee-49d7-8f0f-826b3fc98cf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/a[31]</value>
      <webElementGuid>34aab671-cc89-42f4-bb3b-7cd6a3a49af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Screenshot_20221128_105312.png')]</value>
      <webElementGuid>1a593488-d6f8-443f-b0c3-f71580a2a1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selenium_file.txt'])[1]/following::a[1]</value>
      <webElementGuid>889c937e-a6e1-4990-bea1-d8773ec311c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='build.txt'])[1]/following::a[2]</value>
      <webElementGuid>ce50bb44-20d1-4678-a189-98427b0267ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='file.txt'])[1]/preceding::a[1]</value>
      <webElementGuid>fa4e5b6a-a199-4486-b12d-86009ff187e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Screenshot (23).png'])[1]/preceding::a[2]</value>
      <webElementGuid>b21907e2-7413-4847-adb1-61389a9daa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Screenshot_20221128_105312.png']/parent::*</value>
      <webElementGuid>d19f5ce5-f684-430e-91f0-41f74953dd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/Screenshot_20221128_105312.png')]</value>
      <webElementGuid>b5c42b02-4f48-4cf0-b5bb-ae50cb5badbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[31]</value>
      <webElementGuid>53563eaf-cca4-4850-928a-2642ffe7c91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/Screenshot_20221128_105312.png' and (text() = 'Screenshot_20221128_105312.png' or . = 'Screenshot_20221128_105312.png')]</value>
      <webElementGuid>b99a4e65-964c-4930-bf4e-fcfc15e599f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
